import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import * as path from 'path'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

const recipes = [
  // --- BREAKFAST ---
  {
    title: 'Semiya Upma',
    category: 'Breakfast',
    ingredients: ['2 cups frozen mixed veggies', '1½ teaspoon salt', 'Semiya (vermicelli)'],
    steps: ['Refer to: https://www.youtube.com/watch?v=semiya-upma for full recipe'],
    source_url: null,
    notes: 'Serves 2-3 people',
    servings: '2-3',
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Banana Pancake',
    category: 'Breakfast',
    ingredients: ['1 cup oats flour', '1 banana', '1 egg (optional)', 'Milk'],
    steps: [
      'Grind oats in blender to make oats flour.',
      'Grind egg and banana together, mix with oats flour.',
      'Add milk to make batter like dosa — not too thin nor too thick.',
      'Cook on pan like dosa.',
    ],
    source_url: null,
    notes: 'Healthy oats pancake',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Crispy Chickpea Flatbread',
    category: 'Breakfast',
    ingredients: [
      '1 cup (120g) chickpea flour (gram flour)',
      '1 cup (240ml) water',
      '2 tablespoons olive oil',
      '1 teaspoon salt',
      '1 teaspoon ground cumin',
      '½ teaspoon garlic powder',
      '½ teaspoon paprika',
      '¼ teaspoon black pepper',
      '1 tablespoon lemon juice',
      '2 tablespoons chopped fresh parsley',
      '1 tablespoon chopped fresh rosemary',
      '½ teaspoon baking powder',
      '1 tablespoon sesame seeds (optional)',
    ],
    steps: [
      'In a bowl, whisk together chickpea flour, salt, cumin, garlic powder, paprika, and black pepper.',
      'Slowly add water, whisking continuously until batter is smooth. Stir in olive oil and lemon juice. Rest for 10-15 minutes.',
      'Heat a non-stick pan over medium heat and grease lightly with olive oil.',
      'Stir baking powder into batter. Pour a ladleful into hot pan, spread evenly.',
      'Cook for 3-4 minutes until bubbles form. Flip and cook 2-3 more minutes until golden brown.',
      'Repeat for remaining batter. Sprinkle with parsley, rosemary, and sesame seeds.',
      'Serve warm with hummus, yogurt, or fresh salad.',
    ],
    source_url: null,
    notes: 'Mediterranean-inspired. Crispy and bursting with flavors.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Ragi Kanji',
    category: 'Breakfast',
    ingredients: ['2 tbsp ragi powder', '2 to 2½ mugs water', 'Low fat milk', 'Salt'],
    steps: [
      'Dissolve 2 tbsp ragi powder in 2–2½ mugs water.',
      'Cook on low flame stirring continuously.',
      'Serve with low fat milk and salt.',
    ],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  // --- CHUTNEYS ---
  {
    title: 'Beetroot Chutney',
    category: 'Chutneys',
    ingredients: ['Beetroot', 'Coconut', 'Red chillies', 'Tamarind', 'Salt', 'Oil', 'Mustard seeds', 'Curry leaves'],
    steps: ['Follow recipe at: https://hebbarskitchen.com/beetroot-chutney-recipe-beetroot-pachadi/'],
    source_url: 'https://hebbarskitchen.com/beetroot-chutney-recipe-beetroot-pachadi/',
    notes: null,
    servings: '4',
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Orange Chutney',
    category: 'Chutneys',
    ingredients: [
      '1 onion, cubed',
      '2 tomatoes, cubed',
      '2 red chillies',
      '2 tablespoons oil',
      '1 tsp jeera',
      '1 tbsp urud dal',
      '1 tbsp chana dal',
      '1 inch ginger',
      '2 garlic pods',
      'Turmeric powder',
      '1 tsp salt',
      'Small piece tamarind (optional)',
      'Green chillies',
      'Red chilli powder (if needed)',
    ],
    steps: [
      'Pour oil and fry jeera, urud dal, and chana dal until golden brown.',
      'Add cubed onion and fry. Add ginger, garlic, and green chillies.',
      'Once color changes, add tomatoes. Add turmeric powder and tamarind (optional).',
      'Fry until tomatoes are cooked. Add salt. Cool and make into paste.',
    ],
    source_url: null,
    notes: 'Add red chilli powder if not spicy enough.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Peanut Chutney',
    category: 'Chutneys',
    ingredients: ['Peanuts', 'Green chillies', 'Tamarind', 'Salt', 'Oil', 'Mustard seeds', 'Urud dal', 'Curry leaves'],
    steps: ['Follow recipe at: https://hebbarskitchen.com/peanut-chutney-recipe-groundnut-chutney/'],
    source_url: 'https://hebbarskitchen.com/peanut-chutney-recipe-groundnut-chutney/',
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  // --- APPETIZERS ---
  {
    title: 'Chicken 65',
    category: 'Appetizers',
    ingredients: ['Chicken', '1 egg', 'Red chilli powder', 'Turmeric', 'Ginger garlic paste', 'Corn flour', 'Oil'],
    steps: ['Follow street-style Chicken 65 recipe. Add 1 egg to the batter.'],
    source_url: null,
    notes: 'Serves 2-4',
    servings: '2-4',
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Baked Salmon Meatballs with Avocado Sauce',
    category: 'Appetizers',
    ingredients: [
      '1 lb salmon fillet, skin removed and finely chopped',
      '½ cup breadcrumbs',
      '1 egg, lightly beaten',
      '2 tbsp fresh parsley, chopped',
      '1 tsp garlic powder',
      '½ tsp paprika',
      'Salt and pepper to taste',
      '1 tbsp olive oil',
      '1 ripe avocado',
      '¼ cup sour cream',
      '1 tbsp lemon juice',
      '1 clove garlic, minced',
    ],
    steps: [
      'Preheat oven to 375°F (190°C). Combine salmon, breadcrumbs, egg, parsley, garlic powder, paprika, salt, and pepper.',
      'Form into small meatballs on greased baking sheet. Drizzle with olive oil.',
      'Bake for 12-15 minutes until firm and cooked through.',
      'Blend avocado, sour cream, lemon juice, garlic, salt, and pepper until smooth for the sauce.',
      'Serve meatballs with avocado sauce.',
    ],
    source_url: null,
    notes: null,
    servings: '4',
    cook_time: '30 mins',
    image_url: null,
  },
  {
    title: 'Fish Cutlet',
    category: 'Appetizers',
    ingredients: [
      'Fish',
      '1 tsp turmeric powder',
      '½ tsp salt',
      '1 tsp ginger garlic paste',
      '2 tsp chilly powder',
      '2 onions, finely cut',
      '5 green chillies',
      'Pepper powder',
      'Coriander leaves',
      '2 medium potatoes, pressure cooked and mashed',
      'Eggs (beaten with salt and pepper)',
      'Breadcrumbs',
    ],
    steps: [
      'Wash fish and add turmeric, salt, ginger garlic paste, chilly powder. Pour just enough water to cover and boil.',
      'Mash fish while cooking. When water evaporates, switch off.',
      'In non-stick pan, fry finely cut onions and chillies. Add shredded fish, pepper powder, salt.',
      'Remove any bones. Add finely cut coriander.',
      'Mix mashed potatoes with fish. Taste and adjust seasoning.',
      'Shape into balls/patties. Dip in beaten egg, coat with breadcrumbs.',
      'Fry and serve hot with sauce, mayonnaise, and chips.',
    ],
    source_url: null,
    notes: 'Add coriander leaves after mixing in mashed potatoes.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Nethili Fry',
    category: 'Appetizers',
    ingredients: ['Nethili (anchovies)', '1 tsp turmeric powder', '4-5 tsp chilly powder', 'Salt to taste', 'Oil'],
    steps: [
      'Wash fish with plain warm water. Soak for 5 minutes. Repeat if sandy.',
      'Make paste with turmeric, chilly powder, and salt. Mix evenly with fish.',
      'Keep for some time.',
      'Pour enough oil and fry little by little on medium heat.',
      'Fry some first and taste — add more salt if needed.',
    ],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Savory Chicken Wraps with Garlic Cream Sauce',
    category: 'Appetizers',
    ingredients: [
      '2 chicken breasts, sliced thin',
      '4 whole wheat wraps or tortillas',
      '1 tbsp olive oil',
      '4 cloves garlic, minced',
      '½ cup heavy cream',
      '¼ cup chicken broth',
      '¼ cup grated parmesan',
      'Salt and pepper',
      '½ cup fresh spinach',
      '½ cup shredded mozzarella',
      '1 tbsp fresh parsley',
      '1 tbsp lemon juice',
    ],
    steps: [
      'Cook chicken strips in olive oil, seasoned with salt and pepper, 5-7 minutes until golden. Set aside.',
      'Sauté minced garlic in same pan 1-2 minutes.',
      'Add heavy cream, chicken broth, and parmesan. Simmer 3-4 minutes until thickened.',
      'Return chicken to pan, stir to coat. Add spinach and cook 2-3 minutes until wilted.',
      'Stir in lemon juice, top with mozzarella and parsley.',
      'Spoon onto wraps, roll tightly, slice in half.',
    ],
    source_url: null,
    notes: null,
    servings: '4',
    cook_time: '25 mins',
    image_url: null,
  },
  // --- SOUPS ---
  {
    title: 'Bottle Gourd Soup',
    category: 'Soups',
    ingredients: ['Bottle gourd (lauki)', '1 small potato', 'Milk', 'Salt', 'Pepper', 'Spinach', 'Butter'],
    steps: [
      'Cut bottle gourd and pressure cook with a small potato.',
      'Blend when cool.',
      'Add milk to desired consistency. Add pepper and salt.',
      'When soup is boiling, thinly slice spinach and add.',
      'Simmer for a few minutes. Serve with butter.',
    ],
    source_url: null,
    notes: 'Can use pumpkin instead of bottle gourd.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Corn Soup',
    category: 'Soups',
    ingredients: ['Corn', '1 tsp ghee or butter', '6 pepper corns', '5 garlic pods', '1 medium onion', '1 medium potato (optional)', 'Salt', 'Milk', 'Pepper powder'],
    steps: [
      'Heat ghee and sauté pepper corns, garlic, onion, and potato.',
      'Add corn, stir for a few minutes. Add little salt and 2 mugs water. Cover and pressure cook for 5-7 whistles.',
      'Cool and blend nicely.',
      'Strain, add little water to strained mix, blend again and strain.',
      'Add milk and salt if required. Add pepper powder if desired.',
    ],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  // --- RICE ---
  {
    title: 'Ambur Chicken Biryani',
    category: 'Rice',
    ingredients: ['Chicken', 'Basmati rice', '8 red chillies', 'Onion', 'Tomato', 'Ginger garlic paste', 'Spices'],
    steps: ['Follow Jabbar Bhai special Ambur style biryani recipe.'],
    source_url: null,
    notes: '8 red chillies',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Mutton Biryani',
    category: 'Rice',
    ingredients: ['½ kg mutton', 'Basmati rice', 'Onion', 'Tomato', 'Ginger garlic paste', 'Biryani masala', 'Curd', 'Mint', 'Oil/Ghee'],
    steps: ['Pressure cooker mutton biryani. Follow Jabbar Bhai recipe.'],
    source_url: null,
    notes: null,
    servings: '4',
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Beetroot Rice',
    category: 'Rice',
    ingredients: ['Cooked rice', 'Beetroot', 'Onion', 'Jeera', 'Mustard seeds', 'Curry leaves', 'Spices'],
    steps: ['Follow beetroot pulao / beetroot rice recipe.'],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  // --- CURRIES ---
  {
    title: 'Kadala Curry',
    category: 'Curries',
    ingredients: [
      'Black chickpeas (kadala)',
      'Grated coconut',
      'Chilly powder',
      'Dhania (coriander) powder',
      'Curry leaves',
      '1 medium onion',
      'Oil',
      'Mustard seeds',
      '2 red chillies',
      '½ tsp freshly ground pepper',
      'Salt',
    ],
    steps: [
      'Soak kadala overnight. Wash thoroughly and pressure cook with enough water for 7-8 whistles (or more if needed).',
      'In a kadai, fry grated coconut on low-medium flame to golden brown.',
      'Add chilly powder and dhania powder (ratio 1:4). Fry on very low flame.',
      'Add curry leaves and one medium chopped onion. Cool and make fine smooth paste with water.',
      'In kadai heat oil. Fry mustard seeds, curry leaves, red chillies, and chopped onion.',
      'Add ground paste and cooked kadala. Add salt and pepper.',
    ],
    source_url: 'https://hebbarskitchen.com/kadala-curry-recipe-puttu-kadala-curry/',
    notes: 'Make dhania powder fresh from dhania. Coconut paste is key.',
    servings: '4-5',
    cook_time: '1 hr',
    image_url: null,
  },
  {
    title: 'Pepper Chicken',
    category: 'Curries',
    ingredients: ['2 lbs chicken', 'Pepper', 'Onion', 'Tomato', 'Ginger garlic paste', 'Spices'],
    steps: ['Telangana style spicy chicken curry. Use full masala for 2 lbs chicken.'],
    source_url: null,
    notes: '2 lbs chicken for full masala',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Tindora Curry',
    category: 'Curries',
    ingredients: ['Tindora (kovakkai)', 'Onion', 'Tomato', 'Masala', 'Oil', 'Spices'],
    steps: ['Follow Kovakkai/Tindora masala curry recipe. Good side dish for chapathi.'],
    source_url: null,
    notes: null,
    servings: '4',
    cook_time: '1 hr',
    image_url: null,
  },
  {
    title: 'Prawn Gravy',
    category: 'Curries',
    ingredients: [
      '1 lb / 500g prawns',
      'Salt and turmeric for washing',
      '2-3 onions, finely chopped',
      '1 medium tomato, finely chopped',
      'Coriander leaves',
      'Oil',
      '2 green chillies',
      '3 tsp ginger garlic paste',
      '¾ tsp turmeric powder',
      '1 tbsp red chilli powder',
      '1 tsp garam masala',
      'Salt',
    ],
    steps: [
      'Wash prawns with salt and turmeric.',
      'Fry onions and green chillies in oil. After 2 mins, add ginger garlic paste. Fry till raw smell goes.',
      'Add prawns, stir for 5 minutes.',
      'Add turmeric, chilli powder, garam masala, and salt. Mix well.',
      'After 5 minutes, add tomato. Cover and cook on low flame.',
      'Add a little water, cook till prawns are done.',
      'Add coriander leaves and serve hot.',
    ],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Kerala Fish Curry',
    category: 'Curries',
    ingredients: ['Fish', 'Coconut milk', 'Kudampuli (gambooge)', 'Green chillies', 'Ginger', 'Turmeric', 'Chilli powder', 'Salt'],
    steps: ['Follow Kerala style fish curry (meen vevichathu) recipe.'],
    source_url: 'https://www.alittlebitofspice.com/kerala-style-fish-curry-meen-vevichathu-recipe',
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Beef Fry',
    category: 'Curries',
    ingredients: [
      'Beef',
      'Garlic',
      'Ginger',
      'Turmeric',
      'Salt',
      'Coconut oil',
      'Green chillies',
      'Onions',
      'Cinnamon',
      'Elaichi powder',
      'Curry leaves',
      'Curry masala powder',
      'Pepper',
      'Dark soy sauce',
    ],
    steps: [
      'Cook beef with garlic, ginger, turmeric, and salt in pressure cooker: 2 whistles, then medium-low for 20 minutes.',
      'In a wok, heat coconut oil. Add green chillies, onions, cinnamon, elaichi powder, and curry leaves.',
      'Sauté till golden. Add finely chopped ginger and garlic.',
      'Add curry masala powder and fry well.',
      'Add beef (without soup). Add pepper and check salt.',
      'Add a little dark soy sauce for taste and colour. Fry till done.',
    ],
    source_url: null,
    notes: 'Soy sauce adds colour and taste.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Palak Paneer',
    category: 'Curries',
    ingredients: ['Palak (spinach)', 'Paneer', 'Onion', 'Tomato', 'Ginger garlic paste', 'Spices', 'Cream'],
    steps: ['Follow recipe at: https://indianhealthyrecipes.com/palak-paneer-recipe-easy-paneer-recipes-step-by-step-pics/'],
    source_url: 'https://indianhealthyrecipes.com/palak-paneer-recipe-easy-paneer-recipes-step-by-step-pics/',
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Paaya',
    category: 'Curries',
    ingredients: ['Paya (trotters)', 'Oil', 'Jeera', 'Whole garam masala', 'Bay leaf', 'Cinnamon', 'Onion', 'Tomato', 'Ginger garlic paste', 'Turmeric', 'Chilly powder', 'Coriander powder', 'Jeera powder', 'Curry masala', 'Mint', 'Cilantro', 'Lemon juice (optional)'],
    steps: [
      'Heat oil. Add jeera, whole garam masala, bay leaf, and cinnamon.',
      'Add onion, tomato, ginger garlic paste and cook.',
      'Add turmeric, chilly powder, coriander powder, jeera powder, and curry masala. Mix.',
      'Add paya and lots of water.',
      'Pressure cook for 10+ whistles.',
      'Add mint, cilantro, and lemon juice if desired.',
    ],
    source_url: null,
    notes: 'Mint, cilantro, and lemon juice are optional but recommended.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Drumstick and Brinjal Curry',
    category: 'Curries',
    ingredients: ['Drumstick (pre-cooked)', 'Brinjal', '2 onions', '1 tomato', '¼ tsp ginger garlic paste', 'Chilly powder', '½ tsp dhania powder', 'Curry leaves', 'Salt', 'Oil'],
    steps: [
      'Chop onions and tomato. Heat oil, fry onions with ginger garlic paste.',
      'Add tomato and salt. Pre-cook drumstick.',
      'Cut brinjal lengthwise and add to onion-tomato mix. Fry well.',
      'When brinjal changes colour, add chilly powder and dhania powder. Fry 1-2 minutes.',
      'Add pre-cooked drumstick and very little water. Cover and cook 2-3 minutes.',
      'Remove lid, toss until water evaporates. Check taste. Add curry leaves.',
    ],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  // --- PORIYALS ---
  {
    title: 'Carrot Poriyal',
    category: 'Poriyals',
    ingredients: ['Carrots', 'Mustard seeds', 'Urud dal', 'Curry leaves', 'Green chillies', 'Grated coconut', 'Salt', 'Oil'],
    steps: ['Follow recipe at: http://foodviva.com/south-indian-recipes/carrot-poriyal/'],
    source_url: 'http://foodviva.com/south-indian-recipes/carrot-poriyal/',
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Beans Poriyal',
    category: 'Poriyals',
    ingredients: ['Green beans', 'Mustard seeds', 'Urud dal', 'Curry leaves', 'Green chillies', 'Grated coconut', 'Salt', 'Oil'],
    steps: ['Follow recipe at: http://foodviva.com/south-indian-recipes/beans-poriyal/'],
    source_url: 'http://foodviva.com/south-indian-recipes/beans-poriyal/',
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Beetroot Poriyal',
    category: 'Poriyals',
    ingredients: ['Beetroot', 'Mustard seeds', 'Urud dal', 'Curry leaves', 'Green chillies', 'Grated coconut', 'Salt', 'Oil'],
    steps: ['Follow recipe at: http://foodviva.com/south-indian-recipes/beetroot-poriyal/'],
    source_url: 'http://foodviva.com/south-indian-recipes/beetroot-poriyal/',
    notes: null,
    servings: null,
    cook_time: null,
    image_url: null,
  },
  // --- AIR FRYER ---
  {
    title: 'Crispy Salmon Bites',
    category: 'Air Fryer',
    ingredients: [
      '1 lb salmon fillets, skin removed, cut into bite-sized cubes',
      '2 tbsp olive oil',
      '1 tsp garlic powder',
      '1 tsp paprika',
      '½ tsp black pepper',
      '½ tsp salt',
      '½ cup panko breadcrumbs (optional)',
      'Lemon wedges',
      'Fresh parsley',
    ],
    steps: [
      'Toss salmon bites with olive oil, garlic powder, paprika, black pepper, and salt.',
      'Optionally coat with panko breadcrumbs for extra crunch.',
      'Preheat air fryer to 400°F (200°C).',
      'Place in single layer. Cook 8-10 minutes, shaking halfway.',
      'Garnish with parsley. Serve with lemon wedges and dipping sauce.',
    ],
    source_url: null,
    notes: null,
    servings: '4',
    cook_time: '10 mins',
    image_url: null,
  },
  {
    title: 'Nadi Wings',
    category: 'Air Fryer',
    ingredients: ['Chicken wings', 'Oil', 'Rice flour', 'Paprika', 'Garlic seasoning', 'Chilli powder', 'Cajun seasoning'],
    steps: [
      'Coat wings in oil.',
      'Add dry seasoning: rice flour, paprika, garlic seasoning, chilli powder, cajun seasoning.',
      'Air fry on wings mode at 190-200°C for 18 minutes, turning halfway.',
    ],
    source_url: null,
    notes: 'Lower to 190°C for juicier wings.',
    servings: null,
    cook_time: '18 mins',
    image_url: null,
  },
  {
    title: 'Air Fry Shrimp',
    category: 'Air Fryer',
    ingredients: ['Raw shrimp', 'Turmeric', 'Chilli powder', 'Paprika', 'Salt', 'Lime juice', 'Rice flour'],
    steps: [
      'Mix shrimp with turmeric, chilli powder, paprika, salt, lime juice, and rice flour.',
      'Air fry for 10 minutes total.',
    ],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: '10 mins',
    image_url: null,
  },
  {
    title: 'Bacon-Wrapped Asparagus',
    category: 'Air Fryer',
    ingredients: ['Asparagus', 'Bacon', 'Roasted pepper and garlic seasoning', 'Herbs and garlic seasoning'],
    steps: [
      'Cut off base of asparagus. Bundle 3-4 stalks together.',
      'Wrap each bundle with bacon.',
      'Add seasoning: roasted peppers, garlic, herbs.',
      'Air fry on vegetable setting at 200°C for 16 minutes.',
    ],
    source_url: null,
    notes: null,
    servings: null,
    cook_time: '16 mins',
    image_url: null,
  },
  // --- BAKING ---
  {
    title: 'Blueberry Muffins (No Flour)',
    category: 'Baking',
    ingredients: ['2 bananas, mashed', '1 cup peanut butter', '2 eggs', '1 tsp baking powder', '1 cup blueberries', 'White chocolate chips for topping'],
    steps: [
      'Mix all ingredients together.',
      'Bake at 180°C for 15-20 minutes.',
    ],
    source_url: null,
    notes: 'Flourless and healthy.',
    servings: null,
    cook_time: '20 mins',
    image_url: null,
  },
  {
    title: 'No-Flour Apple Cake',
    category: 'Baking',
    ingredients: ['2 apples', '2 eggs', '1 tsp vanilla sugar', '¾ cup (100g) cocoa powder'],
    steps: [
      'Blend all ingredients together until smooth.',
      'Pour into a greased baking dish.',
      'Bake for 30 minutes at 350°F (175°C).',
    ],
    source_url: null,
    notes: 'Flourless chocolate apple cake.',
    servings: null,
    cook_time: '30 mins',
    image_url: null,
  },
  // --- PREP ---
  {
    title: 'Dosa Batter',
    category: 'Prep',
    ingredients: ['Idli rice (4 parts)', 'Urud dal (1 part)', '1-2 tsp fenugreek seeds', '1 cup poha'],
    steps: [
      'Soak idli rice 4-5 hours. Soak urud dal 3-4 hours.',
      'Grind urud dal 45 minutes. Grind rice 10-20 minutes with fenugreek seeds.',
      'Add poha while grinding rice. Mix both batters with hand.',
      'Ferment 8-14 hours in oven with light on. Turn off light after 8-10 hrs based on rise.',
    ],
    source_url: null,
    notes: 'Ratio 4:1 rice to urud dal.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Ginger Garlic Paste',
    category: 'Prep',
    ingredients: ['¼ kg peeled garlic', '~400g ginger'],
    steps: [
      'Remove skin from ginger, wash thoroughly, cut into small pieces.',
      'Grind ginger first. Add 2 tsp water only if needed.',
      'Remove and grind garlic separately.',
      'Combine both in mixie and blend together.',
    ],
    source_url: null,
    notes: 'Do not add too much water.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
  {
    title: 'Buttermilk',
    category: 'Prep',
    ingredients: ['Ginger (half-finger sized piece)', '½ green chilli', 'Few small onion pieces', 'Ample coriander stems and leaves', 'Mint leaves', 'Pinch of hing powder', '2 tsp jeera powder', 'Salt', 'Water', 'Curd/yogurt'],
    steps: [
      'Add little water and grind all ingredients nicely.',
      'Filter and blend again with more water.',
      'Filter again. Add salt if needed.',
    ],
    source_url: null,
    notes: 'Can use frozen mint leaves.',
    servings: null,
    cook_time: null,
    image_url: null,
  },
]

async function seed() {
  console.log(`Seeding ${recipes.length} recipes...`)
  const { data, error } = await supabase.from('recipes').insert(recipes).select()
  if (error) {
    console.error('Error seeding:', error.message)
    process.exit(1)
  }
  console.log(`✅ Seeded ${data?.length} recipes successfully!`)
}

seed()
